package haproxy

import (
	"bytes"
	"fmt"
	"net"
	"reflect"
	"sort"
	"text/template"

	"github.com/goxang/lbplane/internal/spec"
)

type Config struct {
	Services []Service
}

type Service struct {
	Name        string
	Hostnames   []string
	Balance     string
	HealthCheck string
	TLSCert     string
	Slots       []Slot
}

type Slot struct {
	Address string
	Weight  int
}

func (s Slot) Free() bool { return s.Address == "" }

func (c Config) service(name string) (Service, bool) {
	for _, svc := range c.Services {
		if svc.Name == name {
			return svc, true
		}
	}
	return Service{}, false
}

// Backends keep their previous slots so changes stay reload-free.
func Build(services []spec.Service, previous Config, minSlots int) Config {
	var cfg Config
	for _, s := range services {
		svc := Service{
			Name:        s.Name,
			Hostnames:   append([]string(nil), s.Hostnames...),
			Balance:     s.Balance,
			HealthCheck: s.HealthCheck,
			TLSCert:     s.TLSCert,
		}
		prev, found := previous.service(s.Name)
		if found && len(prev.Slots) >= len(s.Backends) {
			svc.Slots = reuseSlots(prev.Slots, s.Backends)
		} else {
			svc.Slots = freshSlots(s.Backends, max(minSlots, 2*len(s.Backends)))
		}
		cfg.Services = append(cfg.Services, svc)
	}
	sort.Slice(cfg.Services, func(i, j int) bool { return cfg.Services[i].Name < cfg.Services[j].Name })
	return cfg
}

func reuseSlots(previous []Slot, backends []spec.Backend) []Slot {
	desiredWeight := map[string]int{}
	for _, b := range backends {
		desiredWeight[b.Address] = b.EffectiveWeight()
	}

	slots := make([]Slot, len(previous))
	for i, slot := range previous {
		if weight, keep := desiredWeight[slot.Address]; keep {
			slots[i] = Slot{Address: slot.Address, Weight: weight}
			delete(desiredWeight, slot.Address)
		}
	}
	for _, b := range backends {
		if _, pending := desiredWeight[b.Address]; !pending {
			continue
		}
		for i := range slots {
			if slots[i].Free() {
				slots[i] = Slot{Address: b.Address, Weight: b.EffectiveWeight()}
				break
			}
		}
	}
	return slots
}

func freshSlots(backends []spec.Backend, size int) []Slot {
	slots := make([]Slot, size)
	for i, b := range backends {
		slots[i] = Slot{Address: b.Address, Weight: b.EffectiveWeight()}
	}
	return slots
}

// True when only slot contents differ.
func SameShape(a, b Config) bool {
	return reflect.DeepEqual(shape(a), shape(b))
}

func shape(c Config) Config {
	out := Config{Services: make([]Service, len(c.Services))}
	for i, svc := range c.Services {
		svc.Slots = make([]Slot, len(svc.Slots))
		out.Services[i] = svc
	}
	return out
}

// Caller must ensure SameShape(previous, next).
func RuntimeCommands(previous, next Config) []string {
	var commands []string
	for i, svc := range next.Services {
		backend := backendName(svc.Name)
		for j, slot := range svc.Slots {
			old := previous.Services[i].Slots[j]
			server := fmt.Sprintf("%s/%s", backend, serverName(j))
			switch {
			case slot == old:
			case slot.Free():
				commands = append(commands, fmt.Sprintf("set server %s state maint", server))
			case slot.Address != old.Address:
				host, port, _ := net.SplitHostPort(slot.Address)
				commands = append(commands,
					fmt.Sprintf("set server %s addr %s port %s", server, host, port),
					fmt.Sprintf("set server %s weight %d", server, slot.Weight),
					fmt.Sprintf("set server %s state ready", server),
				)
			default:
				commands = append(commands, fmt.Sprintf("set server %s weight %d", server, slot.Weight))
			}
		}
	}
	return commands
}

type RenderOptions struct {
	AdminSocket string
	HTTPPort    int
	HTTPSPort   int
}

func Render(cfg Config, opts RenderOptions) ([]byte, error) {
	certs := map[string]bool{}
	for _, svc := range cfg.Services {
		if svc.TLSCert != "" {
			certs[svc.TLSCert] = true
		}
	}
	var sortedCerts []string
	for cert := range certs {
		sortedCerts = append(sortedCerts, cert)
	}
	sort.Strings(sortedCerts)

	var buf bytes.Buffer
	err := configTemplate.Execute(&buf, struct {
		RenderOptions
		Config
		Certs []string
	}{opts, cfg, sortedCerts})
	return buf.Bytes(), err
}

func backendName(service string) string { return "be_" + service }

func serverName(index int) string { return fmt.Sprintf("s%d", index+1) }

var configTemplate = template.Must(template.New("haproxy").Funcs(template.FuncMap{
	"backend": backendName,
	"server":  serverName,
}).Parse(`# generated by lbplane, do not edit
global
    master-worker
    stats socket {{.AdminSocket}} mode 600 level admin
    log stdout format raw local0

defaults
    mode http
    log global
    option httplog
    timeout connect 5s
    timeout client 30s
    timeout server 30s

frontend http
    bind :{{.HTTPPort}}
{{- if .Certs}}
    bind :{{.HTTPSPort}} ssl{{range .Certs}} crt {{.}}{{end}}
{{- end}}
{{- range .Services}}
    use_backend {{backend .Name}} if { req.hdr(host),field(1,:),lower -m str{{range .Hostnames}} {{.}}{{end}} }
{{- end}}
    default_backend be_unknown

backend be_unknown
    http-request return status 404 content-type text/plain string "no service for this host"
{{range .Services}}
backend {{backend .Name}}
    balance {{.Balance}}
{{- if .HealthCheck}}
    option httpchk GET {{.HealthCheck}}
    http-check expect status 200
{{- end}}
{{- range $i, $slot := .Slots}}
{{- if $slot.Free}}
    server {{server $i}} 127.0.0.1:1 weight 0 check disabled
{{- else}}
    server {{server $i}} {{$slot.Address}} weight {{$slot.Weight}} check
{{- end}}
{{- end}}
{{end}}`))
